apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openobserve.fullname" . }}-alertmanager
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve.labels" . | nindent 4 }}
data:
  # This condition is necessary to ensure backwards compatibility for users
  {{- if .Values.alertmanager.config }}
  ZO_META_CONNECTION_POOL_MIN_SIZE: "{{ .Values.alertmanager.config.ZO_META_CONNECTION_POOL_MIN_SIZE }}"
  ZO_META_CONNECTION_POOL_MAX_SIZE: "{{ .Values.alertmanager.config.ZO_META_CONNECTION_POOL_MAX_SIZE }}"
  ZO_ACTIX_REQ_TIMEOUT: "{{ .Values.alertmanager.config.ZO_ACTIX_REQ_TIMEOUT }}"
  RUST_LOG: "{{ .Values.alertmanager.config.RUST_LOG }}"
  RUST_BACKTRACE: "{{ .Values.alertmanager.config.RUST_BACKTRACE }}"
  {{- else }}
  ZO_META_CONNECTION_POOL_MIN_SIZE: "{{ .Values.config.ZO_META_CONNECTION_POOL_MIN_SIZE }}"
  ZO_META_CONNECTION_POOL_MAX_SIZE: "{{ .Values.config.ZO_META_CONNECTION_POOL_MAX_SIZE }}"
  ZO_ACTIX_REQ_TIMEOUT: "{{ .Values.config.ZO_ACTIX_REQ_TIMEOUT }}"
  RUST_LOG: "{{ .Values.config.RUST_LOG }}"
  RUST_BACKTRACE: "{{ .Values.config.RUST_BACKTRACE }}"
  {{- end }}
